# Generated by Django 5.1.7 on 2025-03-28 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_sale_shipping_cost_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notes about this held sale', verbose_name='Notes')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount of this sale', max_digits=10, verbose_name='Total Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this sale was held', verbose_name='Created At')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer for this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer', verbose_name='Customer')),
                ('user', models.ForeignKey(help_text='User who created this held sale', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Held Sale',
                'verbose_name_plural': 'Held Sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeldSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of product', max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, verbose_name='Unit Price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount for this item', max_digits=10, verbose_name='Discount Amount')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item', max_digits=10, verbose_name='Total Price')),
                ('held_sale', models.ForeignKey(help_text='The held sale this item belongs to', on_delete=django.db.models.deletion.CASCADE, to='inventory.heldsale', verbose_name='Held Sale')),
                ('product', models.ForeignKey(help_text='Product for this sale item', on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Held Sale Item',
                'verbose_name_plural': 'Held Sale Items',
            },
        ),
    ]
