# Generated by Django 5.1.7 on 2025-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_heldsale_heldsaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_tendered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount received from customer', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Change given to customer', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_proforma',
            field=models.BooleanField(default=False, help_text='Whether this is a proforma invoice'),
        ),
        migrations.AddField(
            model_name='sale',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference number for card/mobile payments', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('proforma', 'Proforma'), ('voided', 'Voided')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='inventory_s_status_a36389_idx'),
        ),
    ]
