# Generated by Django 5.1.7 on 2025-03-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_sale_created_at_sale_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_stock', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_items', to='inventory.sale')),
            ],
            options={
                'verbose_name': 'Reserved Stock',
                'verbose_name_plural': 'Reserved Stock',
                'unique_together': {('product', 'sale')},
            },
        ),
    ]
