# Generated by Django 5.1.7 on 2025-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_reservedstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference_id',
            field=models.IntegerField(blank=True, help_text='ID of the related transaction (sale, purchase, etc.)', null=True),
        ),
    ]
