# Generated by Django 5.1.7 on 2025-03-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stockmovement_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
